name: "Broadlink Manager"
description: "Broadlink Manager add-on!"
version: "5.6.0"
slug: "broadlink_manager"
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
startup: before
host_network: true
ports:
  7020/tcp: 7020
options:
  envvars: [
    { "ENABLE_GOOGLE_ANALYTICS": "False" }
  ]
webui: http://[HOST]:[PORT:7020]