name: "Broadlink Manager"
description: "Easely learn and send IR/RF Command"
version: "5.6.9"
slug: "broadlink_manager"
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
startup: before
host_network: true
ports:
  7020/tcp: 7020
# environment:
#   - ENABLE_GOOGLE_ANALYTICS: "False" 
webui: http://[HOST]:[PORT:7020]
url: https://github.com/t0mer/broadlinkmanager-docker