name: "Docker Build"

on:
  workflow_dispatch:
  workflow_run:
    workflows: [Create Release]
    types:
      - completed  


jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Get current date
        id: getDate
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"

      - name: Get semantic version from file
        id: getSemver
        run: echo "::set-output name=semver::$(cat broadlinkmanager/VERSION | tr -d ' \t\n\r' )"

      
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          push: true
          tags: |
            techblog/broadlinkmanager:latest
            techblog/broadlinkmanager:${{ steps.getSemver.outputs.semver }}       

      
      - name: Sign and push docker image
        uses: sudo-bot/action-docker-sign@latest
        with:
          image-ref: "techblog/broadlinkmanager:latest"
          # Example: 51f9a39f3db4ddaaf9174fca69f41fb01a04a4dfb5125ef115feecb93d19efa6
          private-key-id: "${{ secrets.DOCKER_PRIVATE_KEY_ID }}"
          # The contents from: ~/.docker/trust/private/51f9a39f3db4ddaaf9174fca69f41fb01a04a4dfb5125ef115feecb93d19efa6.key)
          private-key: ${{ secrets.DOCKER_PRIVATE_KEY }}
          # Example: myPassw0rdChangeMeReplaceMe
          private-key-passphrase: ${{ secrets.DOCKER_PRIVATE_KEY_PASSPHRASE }}     